
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build image
        run: |
          docker build -t ${{ secrets.REGISTRY_USER }}/portfolio2:${{ github.run_number }} .
          docker build -t ${{ secrets.REGISTRY_USER }}/portfolio2 .

      - name: push image
        run: |
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
          docker push ${{ secrets.REGISTRY_USER }}/portfolio2:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_USER }}/portfolio2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to a server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          #port: ${{ secrets.PORT }}
          script: |
            docker rm -f myresume
            docker run -d --name myresume -p 8080:5001 ${{ secrets.REGISTRY_USER }}/portfolio2:${{ github.run_number }}
```
